### ISSUE TITLE
Event organisers should be able to pre-book dates before they create the event in [meetup|facebook|peatix|etc]]

### ISSUE THREAD

**Issue by miccheng** [webuildsg/webuild#235] opened 2016-05-30 06:02 UTC
Some organisers have a fixed day for their event each month.

Perhaps a recurring event that can be fixed via a pull request to a JSON file?

**Comment by sayanee** [comment] 2016-05-30 06:41
Example of a specific event @miccheng? How many groups on average (out of a total 200+ groups so far) has a fixed day pattern each month?

Either ways, if they already have a fixed date and they create the event on the platform (facebook / meetup / eventbrite), it will automatically appear on webuild.sg. 

JSON file has to be manually maintained. Who will amend it or rather how will we get notified if it changes? It's difficult to get it amended / updated / reminded to be changed in case they do change.  But pulling in events from a platform via API is automatic and the event is confirmed if it appears on webuild.sg.

**Comment by sayanee** [comment] 2016-05-30 06:43
Also each event appears on webuild.sg only if it has a valid address and a description. 

Will the location be confirmed even if the date and time is? A meetup is highly dependant on a location confirmation. 

It's also weird if the description (speaker names and talk titles) are empty.

**Comment by miccheng** [comment] 2016-05-30 07:25
Use case: Creative Crew has a fixed location (NLB Toa Payoh). They also have a fixed day of the month (2nd Tuesdays).

**Comment by miccheng** [comment] 2016-05-30 07:26
I guess he's created the event for the whole year. :P

**Comment by sayanee** [comment] 2016-05-30 09:02
@miccheng yes I rather that the meetup organisers creates the event using the same platform they are already used to instead of adding another "step" of amending webuild.sg's pattern of days.

Maybe initially, we can identify these few meetup groups and ask them to create meetups in the next few months first, observe the pattern and then see how?

I'm closing this issue and happy to open if this creates a lot of planning issues. 

At the end of the day, we are trying to list events that are 99% confirmed and automatically updated with least manual intervention and highest accuracy of information. With this aim, querying the API has given us maximum benifit.

**Closed by sayanee** 2016-05-30 09:02 UTC

**Comment by notthetup** [comment] 2016-05-30 11:37
You'll always have issues with people who don't follow the system. Either because they don't care or don't know. That will break everything. :(
